### ISSUE TITLE
[Question]What happens we have one core node and one or more replicants and the core node fails?

### ISSUE THREAD

**Issue by shivamydv** [emqx/mria#10]
What happens if there is one core node and one or more replicants and the core node fails? How will db recover from this and will be there be data loss?

I could not find anything for this in the readme files, hence this question.

**Comment by k32** [comment]
Hi! 
This is a great question. The replicant nodes won't be able to perform any write transactions while the core cluster is completely down. After the core nodes come alive again, the replicants will recover automatically.

**Comment by shivamydv** [comment]
If there is only one core and it's down, all the writes transactions will fail. This might lead to loss of data right?

**Comment by k32** [comment]
You may think of mria as a regular mnesia cluster + replicant cluster. The kind of faults that lead to loss of data in the regular mnesia will lead to the loss of data in mria as well. However, it strives to never introduce additional data loss scenarios. If it suspects that some data has not been replicated, it just drops everything on the replicant node and copies the entirety of data from the core cluster again. While this is happening, the replicant node will read the data from the core node instead of locally to minimize the disturbance.
